version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: frontend-prod
    ports:
      - "80:80"
    env_file:
      - .env.prod
    networks:
      - luhn-net-prod


networks:
  luhn-net-prod:
    external: true
