version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: frontend-prod
    ports:
      - "80:80"
    env_file:
      - .env.prod
    environment:
      - BACKEND_HOST=backend
    # Se quita el `volumes:` porque no hace falta montar nada
    # Se respeta el CMD del Dockerfile que ya hace envsubst
    networks:
      - luhn-net-prod

networks:
  luhn-net-prod:
    external: true
